#!/bin/bash

export LANG=C
export PATH=/sbin:/bin:/usr/sbin:/usr/bin

set -u

readonly TARGET=$1

set -x

     systemctl status  ${TARGET} -l || exit $?
echo
sudo systemctl restart ${TARGET}
echo
sleep 3
echo
     systemctl status  ${TARGET} -l

exit
